name: Build Android apk
on: workflow_dispatch

jobs:
  build-android-apk:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.22.2'

      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: Decode SSH Key
        run: |
          $base64EncodedKey = "${{ secrets.ENCODED_SSH_PRIVATE_KEY }}"
          $decodedKey = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($base64EncodedKey))
          $sshDir = "$HOME\.ssh"
          New-Item -ItemType Directory -Force -Path $sshDir
          $decodedKey | Out-File -FilePath "$sshDir\id_rsa" -Encoding ascii
          icacls "$sshDir\id_rsa" /inheritance:r /grant:r "$($env:USERNAME):(R,W)"
          ssh-keyscan github.com | Out-File -FilePath "$sshDir\known_hosts" -Encoding ascii
        shell: pwsh

      - name: Clone project
        run: git clone git@github.com:jeetparekh3005/Namma-Music-Main.git Harmony-Music
        shell: pwsh

      - name: Flutter doctor
        run: flutter doctor
        shell: pwsh

      - name: Install project dependencies
        working-directory: ./Harmony-Music
        run: flutter pub get
        shell: pwsh

      - name: Update lang data
        working-directory: ./Harmony-Music
        run: dart localization/generator.dart
        shell: pwsh

      - name: Set update check flag to true
        working-directory: ./Harmony-Music/lib/utils
        run: echo "const updateCheckFlag = true;" > update_check_flag_file.dart
        shell: pwsh

      - name: Build android apk
        working-directory: ./Harmony-Music
        run: |
          flutter build apk --split-per-abi --release
          flutter build apk
        shell: pwsh

      - name: Upload apk artifact
        uses: actions/upload-artifact@v4
        with:
          name: Harmony music apk
          path: ./Harmony-Music/build/app/outputs/flutter-apk/*apk
